apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-entry
spec:
  rules:
  - host: 192.168.0.167
    http:
      paths:
      - path: /api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: gateway-svc
            port:
              number: 80