apiVersion: v1
kind: Service
metadata:
  name: node-port-srv
spec:
  type: NodePort
  selector:
    app: inventory-api
  ports:
    - name: inventory-api
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
    - name: auth-port
      port: 80
      targetPort: 8080
      nodePort: 30001