apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Infrastructure/Database/SqlServer/sql-server-storage.yaml
  - Infrastructure/Database/SqlServer/sql-server-depl.yaml
  - Infrastructure/Database/SqlServer/sql-server-svc.yaml

  - Infrastructure/Gateway/gateway-depl.yaml
  - Infrastructure/Gateway/gateway-svc.yaml

  - Auth/auth-depl.yaml
  - Auth/auth-svc.yaml

  - Inventory/inventory-depl.yaml
  - Inventory/inventory-svc.yaml

  - Recipe/recipe-depl.yaml
  - Recipe/recipe-svc.yaml

  - Infrastructure/Ingress/ingress-entry.yaml

  - app-secrets.secret.yaml
  - edamam-secrets.secret.yaml