apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:  
              secretKeyRef:
                name: app-secrets
                key: sa-password
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433