apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-entry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: foodsense.local
    http:
      paths:
      - path: /api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: gateway-svc
            port:
              number: 80
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: client-svc
            port:
              number: 80