apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
    spec:
      initContainers:
        - name: wait-for-sql
          image: busybox
          command: ['sh', '-c', "until nc -z sql-server-svc 1433; do echo waiting for sql; sleep 2; done"]
      containers:
        - name: recipe-api
          image: ghcr.io/maksm4/foodsense/recipe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RECIPE_CONNECTION
            - name: JwtSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_KEY

            - name: Edamam__AppId
              valueFrom:
                secretKeyRef:
                  name: edamam-secrets
                  key: EDAMAM_APPID

            - name: Edamam__AppKey
              valueFrom:
                secretKeyRef:
                  name: edamam-secrets
                  key: EDAMAM_APPKEY