apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      initContainers:
        - name: wait-for-sql
          image: busybox
          command: ['sh', '-c', "until nc -z sql-server-svc 1433; do echo waiting for sql; sleep 2; done"]
      containers:
        - name: inventory-api
          image: ghcr.io/maksm4/foodsense/inventory:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INVENTORY_CONNECTION
            - name: JwtSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_KEY
            - name: Azure__TranslatorKey 
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: TRANSLATOR_KEY

            - name: Azure__TranslatorRegion
              valueFrom:
                secretKeyRef:
                  name: azure-secrets
                  key: TRANSLATOR_REGION