apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort
  selector:
    app: gateway-api
  ports:
    - name: gateway-port
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
