apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      volumes:
        - name: mssql-data-volume
          persistentVolumeClaim:
            claimName: mssql-data-claim
      
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:  
              secretKeyRef:
                name: app-secrets
                key: SA_PASSWORD
        ports:
        - containerPort: 1433
        
        volumeMounts:
        - name: mssql-data-volume
          mountPath: /var/opt/mssql
